[tools]
node = "22.17.0"

[tasks.setup]
run = [
    "docker compose build",
    "[ -f .env ] || cp .env.example .env"
]

[tasks.up]
run = "docker compose up -d"

[tasks.down]
run = "docker compose down"

[tasks.restart]
run = [
    "mise run down",
    "mise run up"
]
